### ISSUE TITLE
Object not found: http://localhost/ORS/login/ValidedLogin

### ISSUE THREAD

**Issue by enamcse** [arif2009/OnlineRegistrationSystem#1]
![cant login duet](https://user-images.githubusercontent.com/1696846/50697080-6c896700-106b-11e9-9dc0-428e78a1b7c0.JPG)

**Comment by arif2009** [comment]
@enamcse 
1) Make sure your **rewrite module** is enabled. By default, it is enabled in XAMPP.

2) As your localhost folder name is **ORS**, that I see from your screenshot. So you should add the same name into **.htaccess** like below :

![image](https://user-images.githubusercontent.com/6396346/64131519-f94b1700-cdea-11e9-82b0-ac9050de06fd.png)
